### ISSUE TITLE
Modify docs build to output for the Dev Portal

### ISSUE THREAD

**Issue by da1910** [pyansys/openapi-common#281]
### Description of the modifications

Add outputs from the documentation build that can be uploaded to the dev portal

### Useful links and references

See changes in https://github.com/pyansys/pyaedt/pull/1747/files for the necessary outputs. Artifact should be called `<FILL IN>`

**Comment by Andy-Grigg** [comment]
Gate the actual 'push' step so it doesn't happen right now.
